### ISSUE TITLE
support  for python3 

### ISSUE THREAD

**Issue by allan-simon** [yanjost/redmine-cli#4]
are you interested in making it support python3 ?
just checking if the project is still alive before taking time to make a PR :)

**Comment by yanjost** [comment]
Well I'm quite busy at the moment, so feel free to implement it if you want.

You can also list the libraries I'm using and check if they are compatible, that would help.

**Comment by yanjost** [comment]
Hi, I just fixed python 2.6 to 3.4 support, tell me how it goes ...

**Comment by yanjost** [comment]
Support for Python3 is done
